/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calcula.h"

bool_t
xdr_operandos(xdrs, objp)
	XDR *xdrs;
	operandos *objp;
{

	if (!xdr_int(xdrs, &objp->x))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->y))
		return (FALSE);
	return (TRUE);
}
