/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include "calcula.h"

int add(CLIENT *clnt, int x, int y) {
  operandos ops;
  int *result;

  ops.x = x;
  ops.y = y;

  result = add_100(&ops, clnt);
  if (result == NULL) {
    fprintf(stderr, "Problema na chamada RPC\n");
    exit(0);
  }
  return (*result);
}

int sub(CLIENT *clnt, int x, int y) {
  operandos ops;
  int *result;

  ops.x = x;
  ops.y = y;

  result = sub_100(&ops, clnt);
  if (result == NULL) {
    fprintf(stderr, "Problema na chamada RPC\n");
    exit(0);
  }
  return (*result);
}

void
prog_100(host)
char *host;
{
	CLIENT *clnt;
	int  *result_1;
	operandos  add_100_arg;
	int  *result_2;
	operandos  sub_100_arg;
	clnt = clnt_create(host, PROG, VERSAO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = add_100(&add_100_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = sub_100(&sub_100_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}

int main(int argc, char **argv) {
  CLIENT *clnt;
  int x, y;

  if (argc != 4) {
    fprintf(stderr, "Usagem errada\n");
    exit(0);
  }
  clnt = clnt_create(argv[1], PROG, VERSAO, "udp");
  if (clnt == (CLIENT *) NULL) {
    clnt_pcreateerror(argv[1]);
    exit(1);
  }
  x = atoi(argv[2]);
  y = atoi(argv[3]);
  printf("%d + %d = %d\n",x,y, add(clnt,x,y));
  printf("%d - %d = %d\n",x,y, sub(clnt,x,y));

  return 0;
}
