/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "address_book.h"

bool_t
xdr_entry (XDR *xdrs, entry *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->name.name_val, (u_int *) &objp->name.name_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->addr.addr_val, (u_int *) &objp->addr.addr_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->phone.phone_val, (u_int *) &objp->phone.phone_len, ~0,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_entries (XDR *xdrs, entries *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->new, sizeof (entry), (xdrproc_t) xdr_entry))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->old, sizeof (entry), (xdrproc_t) xdr_entry))
		 return FALSE;
	return TRUE;
}
