/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADDRESS_BOOK_H_RPCGEN
#define _ADDRESS_BOOK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct entry {
	struct {
		u_int name_len;
		char *name_val;
	} name;
	struct {
		u_int addr_len;
		char *addr_val;
	} addr;
	struct {
		u_int phone_len;
		char *phone_val;
	} phone;
};
typedef struct entry entry;

struct entries {
	entry *new;
	entry *old;
};
typedef struct entries entries;

#define PROG 999999
#define VERSAO 110

#if defined(__STDC__) || defined(__cplusplus)
#define drop 1
extern  int * drop_110(void *, CLIENT *);
extern  int * drop_110_svc(void *, struct svc_req *);
#define insert 2
extern  int * insert_110(entry *, CLIENT *);
extern  int * insert_110_svc(entry *, struct svc_req *);
#define alter 3
extern  int * alter_110(entries *, CLIENT *);
extern  int * alter_110_svc(entries *, struct svc_req *);
#define delete 4
extern  int * delete_110(entry *, CLIENT *);
extern  int * delete_110_svc(entry *, struct svc_req *);
#define consult 5
extern  entry * consult_110(entry *, CLIENT *);
extern  entry * consult_110_svc(entry *, struct svc_req *);
extern int prog_110_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define drop 1
extern  int * drop_110();
extern  int * drop_110_svc();
#define insert 2
extern  int * insert_110();
extern  int * insert_110_svc();
#define alter 3
extern  int * alter_110();
extern  int * alter_110_svc();
#define delete 4
extern  int * delete_110();
extern  int * delete_110_svc();
#define consult 5
extern  entry * consult_110();
extern  entry * consult_110_svc();
extern int prog_110_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entry (XDR *, entry*);
extern  bool_t xdr_entries (XDR *, entries*);

#else /* K&R C */
extern bool_t xdr_entry ();
extern bool_t xdr_entries ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADDRESS_BOOK_H_RPCGEN */
