/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include "agenda.h"

void initialize(CLIENT *clnt) {
	initialize_10(NULL, clnt);
}

void insert(CLIENT *clnt) {
	data entry;
	entry.name = "anderson";
	entry.addr = "endereco";
	entry.phone = "33563515";
	insert_10(&entry, clnt);
}

void alter(CLIENT *clnt) {
	data_alter entry;
	entry.old_name = "anderson";
	entry.new_name = "manoweng";
	entry.new_addr = "novo endereco";
	entry.new_phone = "51536533";
	alter_10(&entry, clnt);
}
/*
void remove(CLIENT *clnt) {
	data entry;
	entry.name = "manoweng";
	remove_10(&entry, clnt);
}

void consult(CLIENT *clnt) {
	data entry;
	entry.name = "manoweng";
	consult_10(&entry, clnt);
}
*/
void
prog_10(host)
char *host;
{
	CLIENT *clnt;
	void  *result_1;
	char*  initialize_10_arg;
	void  *result_2;
	data  insert_10_arg;
	void  *result_3;
	data_alter  alter_10_arg;
	void  *result_4;
	data  remove_10_arg;
	void  *result_5;
	data  consult_10_arg;
	clnt = clnt_create(host, PROG, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = initialize_10((void*)&initialize_10_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_2 = insert_10(&insert_10_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_3 = alter_10(&alter_10_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_4 = remove_10(&remove_10_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	result_5 = consult_10(&consult_10_arg, clnt);
	if (result_5 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
	clnt_destroy( clnt );
}


main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	// prog_10( host );
	
	CLIENT *clnt;
	clnt = clnt_create(argv[1], PROG, VERSION, "udp");
	
	printf("initialize\n");
	initialize(clnt);
	printf("insert\n");
	insert(clnt);
}
