/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "agenda.h"

bool_t
xdr_data(xdrs, objp)
	XDR *xdrs;
	data *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->name, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->addr, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->phone, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_data_alter(xdrs, objp)
	XDR *xdrs;
	data_alter *objp;
{

	if (!xdr_pointer(xdrs, (char **)&objp->old_name, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->new_name, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->new_addr, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->new_phone, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}
