/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <mysql.h>
#include "agenda.h"

#define SERVER "localhost"
#define USER "root"
#define PASSWORD "toor"
#define DATABASE "aloha"

void *
initialize_10_svc(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static char* result;

	/*
	 * insert server code here
	 */

	return((void*) &result);
}

void *
insert_10_svc(argp, rqstp)
	data *argp;
	struct svc_req *rqstp;
{

	static char* result;
	
	/* colocar a query */

	return((void*) &result);
}

void *
alter_10_svc(argp, rqstp)
	data_alter *argp;
	struct svc_req *rqstp;
{

	static char* result;

	/* colocar a query */

	return((void*) &result);
}

void *
remove_10_svc(argp, rqstp)
	data *argp;
	struct svc_req *rqstp;
{

	static char* result;

	/* colocar a query */

	return((void*) &result);
}

void *
consult_10_svc(argp, rqstp)
	data *argp;
	struct svc_req *rqstp;
{

	static char* result;

	/* colocar a query */

	return((void*) &result);
}
